main: me.ferrybig.minecraftcron.Main
name: MinecraftCron
description: <
    This is a plugin that executes tasks on certain times and uses a java based cron implementation to do.
author: ferrybig
version: ${project.version}
database: no
startup: POSTWORLD
commands:
    minecraftcronreload:
        permission: "minecraftcron.reload"